one_to_two_config:
    N_slm: 49
    slm_pitch: 5
    N_atom: 401
    period: 5
    distance: {
      'd1': 2000,
      't': 1000,
      'd2': 20000
    }
    training: {
      optimizer: 'Adam',
       optim_hparas: {                # hyper-parameters for the optimizer (depends on which optimizer you are using)
          'lr': 0.01                  # learning rate 
          #'betas': (0.1,0.5),          
          #'momentum': 0.5     w         # momentum for SGD
      },
      n_loops: 100,
      early_stop_n: 20
    }
